/**
 * Hermes Report Generator
 * Generates execution reports in various formats
 */

class ReportGenerator {
  constructor() {
    this.formats = ['json', 'markdown', 'html', 'csv'];
  }

  /**
   * Generate report
   */
  generate(workflowExecution, format = 'json') {
    const rawData = this.collectData(workflowExecution);
    
    switch (format) {
      case 'json':
        return this.toJson(rawData);
      case 'markdown':
        return this.toMarkdown(rawData);
      case 'html':
        return this.toHtml(rawData);
      case 'csv':
        return this.toCsv(rawData);
      default:
        return this.toJson(rawData);
    }
  }

  /**
   * Collect execution data
   */
  collectData(execution) {
    const start = execution.startTime;
    const end = execution.endTime || new Date();
    const duration = (end - start) / 1000;

    return {
      report_id: `report-${Date.now()}`,
      workflow_id: execution.workflowId,
      start_time: start.toISOString(),
      end_time: end.toISOString(),
      duration_seconds: duration,
      status: execution.status,
      
      summary: this.summarizeTasks(execution.tasks),
      
      token_usage: this.calculateTokenUsage(execution.tasks),
      
      node_executions: execution.tasks.map(task => ({
        id: task.id,
        type: task.type,
        status: task.status,
        duration: task.duration,
        tokens: task.tokens
      })),
      
      errors: execution.errors || [],
      
      outputs: execution.outputs
    };
  }

  summarizeTasks(tasks) {
    const completed = tasks.filter(t => t.status === 'success').length;
    const failed = tasks.filter(t => t.status === 'error').length;
    const total = tasks.length;

    return {
      total_tasks: total,
      completed_tasks: completed,
      failed_tasks: failed,
      success_rate: total > 0 ? Math.round((completed / total) * 100) : 0
    };
  }

  calculateTokenUsage(tasks) {
    const total = tasks.reduce((sum, t) => sum + (t.tokens || 0), 0);
    
    const byAgent = {};
    tasks.forEach(task => {
      byAgent[task.type] = (byAgent[task.type] || 0) + (task.tokens || 0);
    });

    return {
      total,
      by_agent: byAgent,
      cost_estimate: this.estimateCost(total)
    };
  }

  estimateCost(totalTokens) {
    // Rough estimate: $3 per 1M tokens for GPT-4o
    return (totalTokens / 1000000) * 3;
  }

  toJson(data) {
    return JSON.stringify(data, null, 2);
  }

  toMarkdown(data) {
    const statusEmoji = data.status === 'success' ? '✅' : '❌';
    
    return `# Workflow Execution Report\n\n` +
           `## Summary\n\n` +
           `- **Status**: ${statusEmoji} ${data.status}\n` +
           `- **Duration**: ${Math.round(data.duration_seconds / 60)} min ${data.duration_seconds % 60} sec\n` +
           `- **Tasks**: ${data.summary.completed_tasks} completed, ${data.summary.failed_tasks} failed\n\n` +
           `## Token Usage\n\n` +
           `- **Total**: ${data.token_usage.total.toLocaleString()} tokens\n` +
           `- **Est. Cost**: $${data.token_usage.cost_estimate.toFixed(4)}\n\n` +
           `---\n\n_Generated by Hermes AI Orchestrator_`;
  }

  toHtml(data) {
    return `
<!DOCTYPE html>
<html>
<head>
  <title>Hermes Report</title>
  <style>
    body { font-family: 'Inter', sans-serif; max-width: 900px; margin: 40px auto; padding: 20px; }
    .success { color: #61DDAA; }
    .error { color: #FF6B6B; }
  </style>
</head>
<body>
  <h1>Hermes Execution Report</h1>
  <p><strong>Status:</strong> <span class="${data.status}">${data.status}</span></p>
  <p><strong>Duration:</strong> ${data.duration_seconds.toFixed(1)}s</p>
  <h2>Summary</h2>
  <pre>${JSON.stringify(data.summary, null, 2)}</pre>
</body>
</html>
    `;
  }

  toCsv(data) {
    const headers = 'Agent,Tasks,Tokens,Duration';
    const rows = data.node_executions.map(node => 
      `${node.type},1,${node.tokens},${node.duration}`
    );
    return [headers, ...rows].join('\n');
  }
}

module.exports = { ReportGenerator };
